url: ''
baseurl: ''
title: "La Conjoncture"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  artists:
    output: true
    permalink: /les-artistes/:slug
  events:
    output: false
    future: true
    sort_by: date
  projects:
    output: true
    permalink: /projets/:slug
    sort_by: order

