url: ''
baseurl: ''
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  artists:
    output: true
    permalink: /les-artistes/:slug

